version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: debatex-postgres

    restart: always

    environment:
      POSTGRES_USER: debatex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: debatex

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: